language_ext_map = {'dyalog': 'APL', 'apl': 'APL', 'asc': 'PGP', 'pgp': 'PGP', 'sig': 'SML', 'asn': 'ASN.1',
                    'asn1': 'ASN.1', 'b': 'Brainfuck', 'bf': 'Brainfuck', 'c': 'C', 'h': 'C', 'ino': 'C', 'cpp': 'C++',
                    'c++': 'C++', 'cc': 'C++', 'cxx': 'C++', 'hpp': 'C++', 'h++': 'C++', 'hh': 'C++', 'hxx': 'C++',
                    'cob': 'Cobol', 'cpy': 'Cobol', 'cs': 'C#', 'clj': 'Clojure', 'cljc': 'Clojure', 'cljx': 'Clojure',
                    'cljs': 'ClojureScript', 'gss': 'Closure Stylesheets (GSS)', 'cmake': 'CMake', 'cmake.in': 'CMake',
                    'coffee': 'CoffeeScript', 'cl': 'Common Lisp', 'lisp': 'Common Lisp', 'el': 'Common Lisp',
                    'cyp': 'Cypher', 'cypher': 'Cypher', 'pyx': 'Cython', 'pxd': 'Cython', 'pxi': 'Cython',
                    'cr': 'Crystal',
                    'css': 'CSS', 'cql': 'CQL', 'd': 'D', 'dart': 'Dart', 'diff': 'diff', 'patch': 'diff', 'dtd': 'DTD',
                    'dylan': 'Dylan', 'dyl': 'Dylan', 'intr': 'Dylan', 'ecl': 'ECL', 'edn': 'edn', 'e': 'Eiffel',
                    'elm': 'Elm', 'ejs': 'Embedded Javascript', 'erb': 'Embedded Ruby', 'erl': 'Erlang',
                    'factor': 'Factor',
                    'forth': 'Forth', 'fth': 'Forth', '4th': 'Forth', 'f': 'Fortran', 'for': 'Fortran',
                    'f77': 'Fortran',
                    'f90': 'Fortran', 'fs': 'F#', 's': 'Gas', 'feature': 'Gherkin', 'go': 'Go', 'groovy': 'Groovy',
                    'gradle': 'Groovy', 'haml': 'HAML', 'hs': 'Haskell', 'lhs': 'Haskell (Literate)', 'hx': 'Haxe',
                    'hxml': 'HXML', 'aspx': 'ASP.NET', 'html': 'HTML', 'htm': 'HTML', 'handlebars': 'HTML',
                    'hbs': 'HTML',
                    'pro': 'IDL', 'jade': 'Pug', 'pug': 'Pug', 'java': 'Java', 'jsp': 'Java Server Pages',
                    'js': 'JavaScript', 'json': 'JSON', 'map': 'JSON', 'jsonld': 'PEG.js', 'jsx': 'JSX', 'j2': 'Jinja2',
                    'jinja': 'Jinja2', 'jinja2': 'Jinja2', 'jl': 'Julia', 'kt': 'Kotlin', 'less': 'LESS',
                    'ls': 'LiveScript', 'lua': 'Lua', 'markdown': 'Markdown', 'md': 'Markdown', 'mkd': 'Markdown',
                    'm': 'Octave', 'nb': 'Mathematica', 'mo': 'Modelica', 'mps': 'MUMPS', 'mbox': 'mbox', 'nsh': 'NSIS',
                    'nsi': 'NSIS', 'nt': 'NTriples', 'nq': 'NTriples', 'mm': 'Objective-C', 'ml': 'OCaml',
                    'mli': 'OCaml',
                    'mll': 'OCaml', 'mly': 'OCaml', 'oz': 'Oz', 'p': 'Pascal', 'pas': 'Pascal', 'pl': 'Perl',
                    'pm': 'Perl',
                    'php': 'PHP', 'php3': 'PHP', 'php4': 'PHP', 'php5': 'PHP', 'php7': 'PHP', 'phtml': 'PHP',
                    'pig': 'Pig',
                    'txt': 'Plain Text', 'text': 'LaTeX', 'conf': 'Plain Text', 'def': 'Plain Text',
                    'list': 'Plain Text',
                    'log': 'Plain Text', 'pls': 'PLSQL', 'ps1': 'PowerShell', 'psd1': 'PowerShell',
                    'psm1': 'PowerShell',
                    'properties': 'Properties files', 'ini': 'Properties files', 'in': 'Properties files',
                    'proto': 'ProtoBuf', 'BUILD': 'Python', 'bzl': 'Python', 'py': 'Python', 'pyw': 'Python',
                    'pp': 'Puppet', 'q': 'Q', 'r': 'R', 'R': 'R', 'rst': 'reStructuredText', 'spec': 'RPM Spec',
                    'rb': 'Ruby', 'rs': 'Rust', 'sas': 'SAS', 'sass': 'Sass', 'scala': 'Scala', 'scm': 'Scheme',
                    'ss': 'Scheme', 'scss': 'SCSS', 'sh': 'Shell', 'ksh': 'Shell', 'bash': 'Shell', 'siv': 'Sieve',
                    'sieve': 'Sieve', 'slim': 'Slim', 'st': 'Smalltalk', 'tpl': 'Smarty', 'sml': 'SML', 'fun': 'SML',
                    'smackspec': 'SML', 'soy': 'Soy', 'rq': 'SPARQL', 'sparql': 'SPARQL', 'sql': 'SQL',
                    'nut': 'Squirrel',
                    'styl': 'Stylus', 'swift': 'Swift', 'ltx': 'LaTeX', 'tex': 'LaTeX', 'v': 'Verilog',
                    'sv': 'SystemVerilog', 'svh': 'SystemVerilog', 'tcl': 'Tcl', 'textile': 'Textile', 'toml': 'TOML',
                    '1': 'troff', '2': 'troff', '3': 'troff', '4': 'troff', '5': 'troff', '6': 'troff', '7': 'troff',
                    '8': 'troff', '9': 'troff', 'ttcn': 'TTCN', 'ttcn3': 'TTCN', 'ttcnpp': 'TTCN', 'cfg': 'TTCN_CFG',
                    'ttl': 'Turtle', 'ts': 'TypeScript', 'tsx': 'TypeScript-JSX', 'webidl': 'Web IDL', 'vb': 'VB.NET',
                    'vbs': 'VBScript', 'vtl': 'Velocity', 'vhd': 'VHDL', 'vhdl': 'VHDL', 'vue': 'Vue.js Component',
                    'xml': 'XML', 'xsl': 'XML', 'xsd': 'XML', 'svg': 'XML', 'xy': 'XQuery', 'xquery': 'XQuery',
                    'ys': 'Yacas', 'yaml': 'YAML', 'yml': 'YAML', 'z80': 'Z80', 'mscgen': 'mscgen', 'mscin': 'mscgen',
                    'msc': 'mscgen', 'xu': 'xu', 'msgenny': 'msgenny'}
